# Generated by Django 4.2.7 on 2023-11-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('u_age', models.IntegerField()),
                ('u_gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
